---
# Home Assistant component
# # https://wwww.home-assistant.io/docs/configuration/basic/

homeassistant:
  # Customize individual entities
  customize: !include_dir_merge_named ../customizations/entities

  # Customize all entities in a domain
  customize_domain: !include_dir_merge_named ../customizations/domains

  # Customize entities based on a matching pattern
  customize_glob: !include_dir_merge_named ../customizations/globs

  allowlist_external_dirs:
    - /config/blueprints/automation/panhans
