# Modus Halloween

# True if current date is the Halloween date

sensor:
  - name: "Modus Halloween"
    unique_id: modus_halloween
    icon: "mdi:halloween"
    state: >
      {% set current_date = now().strftime('%m-%d') %}
      {{ current_date == '10-31' }}
