sensor:
  - name: "Modus Homeoffice beide"
    unique_id: modus_homeoffice_beide
    icon: "mdi:chair-rolling"
    state: >
      {{ is_state('input_boolean.modus_homeoffice_steffi', 'on')
         and is_state('input_boolean.modus_homeoffice_jan', 'on') }}

  - name: "Modus Homeoffice generell"
    unique_id: modus_homeoffice_generell
    icon: "mdi:chair-rolling"
    state: >
      {{ is_state('input_boolean.modus_homeoffice_steffi', 'on')
         or is_state('input_boolean.modus_homeoffice_jan', 'on') }}

# platform: template
# sensors:
#   modus_homeoffice_beide:
#     friendly_name: "Modus Homeoffice beide"
#     unique_id: modus_homeoffice_beide
#     icon_template: mdi:rchair-rolling
#     value_template: >-
#       {{ is_state('input_boolean.modus_homeoffice_steffi', 'on') and is_state('input_boolean.modus_homeoffice_jan', 'on') }}

#   modus_homeoffice_generell:
#     friendly_name: "Modus Homeoffice generell"
#     unique_id: modus_homeoffice_generell
#     icon_template: mdi:chair-rolling
#     value_template: >-
#       {{ is_state('input_boolean.modus_homeoffice_steffi', 'on') or is_state('input_boolean.modus_homeoffice_jan', 'on') }}
