sensor:
  - name: "Frost erwartet"
    unique_id: frost_tomorrow
    icon: "mdi:snowflake-alert"
    state: >
      {% set forecast = state_attr('weather.cast_home_assistant', 'forecast') %}
      {% if forecast and forecast | count > 1 %}
        {% set tomorrow = forecast[1] %}
        {{ (tomorrow.templow | float(99)) <= 1 }}
      {% else %}
        false
      {% endif %}

# platform: template
# sensors:
#   frost_tomorrow:
#     friendly_name: "Frost erwartet"
#     unique_id: frost_tomorrow
#     icon_template: mdi:snowflake-alert
#     value_template: >
#       {% set forecast = state_attr('weather.cast_home_assistant', 'forecast') %}
#       {% if forecast %}
#         {% set tomorrow = forecast[1] %}
#         {% if tomorrow.templow <= 1 %}
#           true
#         {% else %}
#           false
#         {% endif %}
#       {% else %}
#         false
#       {% endif %}
