sensor:
  - name: "Frost erwartet"
    unique_id: frost_tomorrow
    icon: "mdi:snowflake-alert"
    state: >
      {% set forecast = state_attr('weather.cast_home_assistant', 'forecast') %}
      {% if forecast and forecast | count > 1 %}
        {% set tomorrow = forecast[1] %}
        {{ (tomorrow.templow | float(99)) <= 1 }}
      {% else %}
        false
      {% endif %}
