sensor:
  - name: "Regen erwartet"
    unique_id: modus_rain_tomorrow
    icon: "mdi:weather-rainy"
    state: >
      {% set forecast = state_attr('weather.forecast_home_assistant', 'forecast') %}
      {% if forecast and forecast | count > 1 %}
        {% set tomorrow = forecast[1] %}
        {{ 'rain' in tomorrow.condition | default('') }}
      {% else %}
        false
      {% endif %}
