binary_sensor:
  - name: "Dachfenster links Zustand"
    unique_id: dachfenster_links_zustand
    device_class: window
    state: >
      {{ (state_attr('cover.dachfenster_links', 'current_position') | int(0)) != 0 }}
    icon: >
      {% if (state_attr('cover.dachfenster_links', 'current_position') | int(0)) != 0 %}
        phu:tilt-window-open
      {% else %}
        phu:tilt-window-closed
      {% endif %}

  - name: "Dachfenster rechts Zustand"
    unique_id: dachfenster_rechts_zustand
    device_class: window
    state: >
      {{ (state_attr('cover.dachfenster_rechts', 'current_position') | int(0)) != 0 }}
    icon: >
      {% if (state_attr('cover.dachfenster_rechts', 'current_position') | int(0)) != 0 %}
        phu:tilt-window-open
      {% else %}
        phu:tilt-window-closed
      {% endif %}

# platform: template
# sensors:
#   dachfenster_links:
#     friendly_name: Dachfenster links Zustand
#     device_class: window
#     unique_id: dachfenster_links_zustand
#     value_template: >-
#       {% if state_attr('cover.dachfenster_links', 'current_position') != 0 %}
#         on
#       {% else %}
#         off
#       {% endif %}
#     icon_template: >-
#       {% if state_attr('cover.dachfenster_links', 'current_position') != 0 %}
#         phu:tilt-window-closed
#       {% else %}
#         phu:tilt-window-open
#       {% endif %}

#   dachfenster_rechts:
#     friendly_name: Dachfenster rechts Zustand
#     device_class: window
#     unique_id: dachfenster_rechts_zustand
#     value_template: >-
#       {% if state_attr('cover.dachfenster_rechts', 'current_position') != 0 %}
#         on
#       {% else %}
#         off
#       {% endif %}
#     icon_template: >-
#       {% if state_attr('cover.dachfenster_rechts', 'current_position') != 0 %}
#         phu:tilt-window-closed
#       {% else %}
#         phu:tilt-window-open
#       {% endif %}
