---

# common/defaults/button.yaml

button:
  - platform: restart
    name: "Restart"

  - platform: safe_mode
    id: button_safe_mode
    name: "${control_name_safe_mode_boot}"

  - platform: factory_reset
    id: factory_reset_btn
    name: "${control_name_factory_reset}"

