---

# common/defaults/text_sensor.yaml

text_sensor:
  - platform: version
    name: ${sensor_name_version}
    icon: ${icon_version}
    hide_timestamp: true
    hide_hash: true

  - platform: template
    name: ${sensor_name_config_tested}
    id: info_config_tested
    icon: ${icon_config_tested}
    lambda: |-
      return {"${config_tested_date}"};

  - platform: template
    name: ${sensor_name_devicename}
    id: info_devicename
    icon: ${icon_devicename}
    lambda: |-
      return {"${devicename}"};

  - platform: template
    name: ${sensor_name_devicename_friendly}
    id: info_friendly_devicename
    icon: ${icon_devicename_friendly}
    lambda: |-
      return {"${friendly_devicename}"};

  - platform: wifi_info
    ip_address:
      name: ${sensor_name_ip_address}
      icon: ${icon_ip_address}
    ssid:
      name: ${sensor_name_connected_ssid}
      icon: ${icon_connected_ssid}
    bssid:
      name: ${sensor_name_connected_bssid}
      icon: ${icon_connected_bssid}
    mac_address:
      name: ${sensor_name_mac_address}
      icon: ${icon_mac_address}
    scan_results:
      name: ${sensor_name_latest_scan_results}
      icon: ${icon_latest_scan_results}
    dns_address:
      name: ${sensor_name_dns_address}
      icon: ${icon_dns_address}

