---

# device_types/sonoff/pow-r2-switch.yaml

packages:
  generic: !include pow-r2-generic.yaml
  
switch:
  - platform: output
    id: relay
    name: ${relay_name}
    icon: ${relay_icon}
    output: relay_output
    on_turn_on:
      - switch.turn_on: button_switch
    on_turn_off:
      - switch.turn_off: button_switch

