---

# components/energy_sensor.yaml

substitutions:
  update_interval: 10s

sensor:
  - platform: integration
    name: "${friendly_devicename} Energie"
    sensor: power_wattage
    time_unit: h
    restore: true
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO04
    change_mode_every: 4
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    update_interval: 3s

    power:
      name: "${friendly_devicename} Leistung"
      unit_of_measurement: W
      id: power_wattage
      icon: mdi:lightning-bolt
      filters:
        - throttle_average: ${update_interval}

    voltage:
      name: "${friendly_devicename} Spannung"
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline
      disabled_by_default: true
      filters:
        - throttle_average: ${update_interval}

    current:
      name: "${friendly_devicename} Stromstärke"
      unit_of_measurement: A
      accuracy_decimals: 3
      icon: mdi:current-ac
      filters:
        - throttle_average: ${update_interval}

  - platform: total_daily_energy
    name: "Energie heute"
    power_id: power_wattage
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 3
    restore: true
    filters:
      - multiply: 0.001
    icon: mdi:calendar-clock
    disabled_by_default: true

