---

# components/sensor/hlw8012.yaml

substitutions:
  update_interval: 10s
  current_res: "0.00280"
  voltage_div: "775"

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO04
    change_mode_every: 4
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    update_interval: ${update_interval}

    power:
      name: ${sensor_name_power}
      icon: ${icon_power}
      id: power_wattage
      unit_of_measurement: ${unit_power}
      filters:
        - throttle_average: ${update_interval}

    voltage:
      name: ${sensor_name_voltage}
      icon: ${icon_voltage}
      id: voltage_sensor
      unit_of_measurement: ${unit_voltage}
      accuracy_decimals: 1
      disabled_by_default: true
      filters:
        - throttle_average: ${update_interval}

    current:
      name: ${sensor_name_current}
      icon: ${icon_current}
      id: current_sensor
      unit_of_measurement: ${unit_current}
      accuracy_decimals: 3
      disabled_by_default: true
      filters:
        - throttle_average: ${update_interval}

