---

# components/power-meter-common.yaml

sensor:
  - platform: integration
    name: ${sensor_name_energy}
    icon: ${icon_energy}
    sensor: power_wattage
    time_unit: ${unit_hours}
    restore: true
    unit_of_measurement: ${unit_energy_kwh}
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    name: ${sensor_name_energy_today}
    icon: ${icon_energy_today}
    power_id: power_wattage
    unit_of_measurement: ${unit_energy_kwh}
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 3
    restore: true
    filters:
      - multiply: 0.001
    disabled_by_default: true

