---

# components/power-meter-cse7766.yaml

substitutions:
  update_interval: 10s

sensor:
  - platform: cse7766
    power:
      name: ${sensor_name_power}
      icon: ${icon_power}
      id: power_wattage
      unit_of_measurement: ${unit_power}
      accuracy_decimals: 1
      filters:
        - throttle_average: ${update_interval}

    voltage:
      name: ${sensor_name_voltage}
      icon: ${icon_voltage}
      id: voltage_sensor
      unit_of_measurement: ${unit_voltage}
      accuracy_decimals: 1
      disabled_by_default: true
      filters:
        - throttle_average: ${update_interval}

    current:
      name: ${sensor_name_current}
      icon: ${icon_current}
      id: current_sensor
      unit_of_measurement: ${unit_current}
      accuracy_decimals: 3
      disabled_by_default: true
      filters:
        - throttle_average: ${update_interval}

    apparent_power:
      name: ${sensor_name_apparent_power}
      icon: ${icon_apparent_power}
      id: apparent_power
      unit_of_measurement: ${unit_apparent_power}
      accuracy_decimals: 1
      disabled_by_default: true
      filters:
        - throttle_average: ${update_interval}

    reactive_power:
      name: ${sensor_name_reactive_power}
      icon: ${icon_reactive_power}
      id: reactive_power
      unit_of_measurement: ${unit_reactive_power}
      accuracy_decimals: 1
      disabled_by_default: true
      filters:
        - throttle_average: ${update_interval}

    power_factor:
      name: ${sensor_name_power_factor}
      icon: ${icon_power_factor}
      id: power_factor
      accuracy_decimals: 2
      disabled_by_default: true
      filters:
        - throttle_average: ${update_interval}

