---

# components/text_sensor.yaml

text_sensor:
  - platform: version
    name: "Version"
    icon: mdi:cube-outline
    hide_timestamp: true
    hide_hash: true

  - platform: template
    name: "Configuration tested"
    id: info_config_tested
    icon: mdi:check
    lambda: |-
      return {"${config_tested_date}"};

  - platform: template
    name: "Devicename"
    id: info_devicename
    icon: mdi:information-box
    lambda: |-
      return {"${devicename}"};

  - platform: template
    name: "Devicename Friendly"
    id: info_friendly_devicename
    icon: mdi:information-box
    lambda: |-
      return {"${friendly_devicename}"};

  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: MAC Address
    scan_results:
      name: Latest Scan Results
    dns_address:
      name: DNS Address

