---

# common/default-components.yaml

packages:
  components_binary_sensor: !include defaults/binary_sensor.yaml
  components_button: !include defaults/button.yaml
  components_sensor: !include defaults/sensor.yaml
  components_text_sensor: !include defaults/text_sensor.yaml
  components_switch: !include defaults/switch.yaml