# common/section-system.yaml

# Home Assistant API
api:
  encryption:
    key: !secret api_key

# Captive Portal
captive_portal:

# Logger
logger:
    level: WARN

# mDNS
mdns:
  disabled: false

# OTA
ota:
  - platform: esphome
    id: ota_pw
    password: !secret ota_password
    # OTA password change
    #password: ${old_ota_password}

# Time
time:
  - platform: homeassistant
    id: homeassistant_time

# Web Server
web_server:
  port: !secret web_server_port
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

# Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # domain: !secret domain
  fast_connect: true
  min_auth_mode: WPA2
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Setup ${friendly_devicename}"
    password: !secret fallback_hotspot_password
    #manual_ip:
      #static_ip: !secret fallback_hotspot_static_ip
      #gateway: !secret fallback_hotspot_gateway
      #subnet: !secret fallback_hotspot_subnet
