# devicetypes/blitzwolf-shp9.yaml

esp8266:
  board: esp8285
  restore_from_flash: true

binary_sensor:
  - platform: gpio
    id: pushbutton
    internal: true
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    # Select which relay to toggle on button press
    # Use either "switch.toggle" or "light.toggle"
    on_press:
      - switch.toggle: relay3

switch:
  # Relay 1 = Staubsauger
  - platform: gpio
    pin: GPIO12
    id: relay1
    name: ${relay_1_name}
    icon: ${relay_1_icon}

  # Relay 3 = Sockel 3
  - platform: gpio
    pin: GPIO5
    id: relay3
    name: ${relay_3_name}
    icon: ${relay_3_icon}

  # Relay 4 = USB ports
  - platform: gpio
    pin: GPIO15
    id: relay4
    name: ${relay_4_name}
    icon: ${relay_4_icon}

output:
  # Relay 2 = Kellertreppe
  - platform: gpio
    id: light_relay
    pin: GPIO14

light:
  - platform: binary
    id: relay2
    name: ${relay_2_name}
    icon: ${relay_2_icon}
    output: light_relay