---

# devicetypes/gosund-sp111.yaml

substitutions:
  update_interval: 10s
  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"

esp8266:
  board: esp8285
  restore_from_flash: true

esphome:
  on_boot:
    priority: -100
    then:
      - switch.template.publish:
          id: on_after_boot_switch
          state: !lambda 'return id(on_after_boot_global);'
      - switch.template.publish:
          id: enable_button_switch
          state: !lambda 'return id(enable_button_global);'
      - switch.template.publish:
          id: allow_turn_off_switch
          state: !lambda 'return id(allow_turn_off_global);'
      - switch.template.publish:
          id: enable_led_switch
          state: !lambda 'return id(enable_led_global);'

      - if:
          condition:
            lambda: 'return id(on_after_boot_global);'
          then:
            - switch.turn_on: button_switch
          else:
            - switch.turn_off: button_switch

      - if:
          condition:
            lambda: 'return id(enable_led_global) && id(relay).state;'
          then:
            - output.turn_on: led_red
          else:
            - output.turn_off: led_red

globals:
  - id: on_after_boot_global
    type: bool
    restore_value: yes
    initial_value: 'true'

  - id: enable_button_global
    type: bool
    restore_value: yes
    initial_value: 'true'

  - id: allow_turn_off_global
    type: bool
    restore_value: yes
    initial_value: 'true'

  - id: enable_led_global
    type: bool
    restore_value: yes
    initial_value: 'true'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    id: ${devicename}_button_state
    on_press:
      - if:
          condition:
            lambda: 'return id(enable_button_global);'
          then:
            - if:
                condition:
                  lambda: 'return id(allow_turn_off_global) || !id(relay).state;'
                then:
                  - switch.toggle: button_switch
                else:
                  - switch.turn_on: button_switch

status_led:
  pin:
    number: GPIO02
    inverted: true
  id: led_blue_status

output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led_red

switch:
  - platform: template
    name: "${friendly_devicename}"
    id: button_switch
    icon: mdi:power
    optimistic: true
    restore_mode: DISABLED
    lambda: |-
      return id(relay).state;
    turn_on_action:
      - switch.turn_on: relay
      - if:
          condition:
            lambda: 'return id(enable_led_global);'
          then:
            - output.turn_on: led_red
          else:
            - output.turn_off: led_red
      - switch.template.publish:
          id: button_switch
          state: ON
    turn_off_action:
      - if:
          condition:
            lambda: 'return id(allow_turn_off_global);'
          then:
            - switch.turn_off: relay
            - output.turn_off: led_red
            - switch.template.publish:
                id: button_switch
                state: OFF
          else:
            - switch.template.publish:
                id: button_switch
                state: ON

  - platform: template
    name: "${friendly_devicename} On after boot"
    id: on_after_boot_switch
    icon: mdi:power-cycle
    optimistic: true
    restore_mode: DISABLED
    lambda: |-
      return id(on_after_boot_global);
    turn_on_action:
      - globals.set:
          id: on_after_boot_global
          value: 'true'
      - switch.template.publish:
          id: on_after_boot_switch
          state: ON
    turn_off_action:
      - globals.set:
          id: on_after_boot_global
          value: 'false'
      - switch.template.publish:
          id: on_after_boot_switch
          state: OFF

  - platform: template
    name: "${friendly_devicename} Enable Button"
    id: enable_button_switch
    icon: mdi:gesture-tap-button
    optimistic: true
    restore_mode: DISABLED
    lambda: |-
      return id(enable_button_global);
    turn_on_action:
      - globals.set:
          id: enable_button_global
          value: 'true'
      - switch.template.publish:
          id: enable_button_switch
          state: ON
    turn_off_action:
      - globals.set:
          id: enable_button_global
          value: 'false'
      - switch.template.publish:
          id: enable_button_switch
          state: OFF

  - platform: template
    name: "${friendly_devicename} Allow Turn Off"
    id: allow_turn_off_switch
    icon: mdi:lock-open-variant
    optimistic: true
    restore_mode: DISABLED
    lambda: |-
      return id(allow_turn_off_global);
    turn_on_action:
      - globals.set:
          id: allow_turn_off_global
          value: 'true'
      - switch.template.publish:
          id: allow_turn_off_switch
          state: ON
    turn_off_action:
      - globals.set:
          id: allow_turn_off_global
          value: 'false'
      - switch.template.publish:
          id: allow_turn_off_switch
          state: OFF

  - platform: template
    name: "${friendly_devicename} Enable LED"
    id: enable_led_switch
    icon: mdi:led-on
    optimistic: true
    restore_mode: DISABLED
    lambda: |-
      return id(enable_led_global);
    turn_on_action:
      - globals.set:
          id: enable_led_global
          value: 'true'
      - switch.template.publish:
          id: enable_led_switch
          state: ON
      - if:
          condition:
            lambda: 'return id(relay).state;'
          then:
            - output.turn_on: led_red
          else:
            - output.turn_off: led_red
    turn_off_action:
      - globals.set:
          id: enable_led_global
          value: 'false'
      - switch.template.publish:
          id: enable_led_switch
          state: OFF
      - output.turn_off: led_red

  - platform: gpio
    pin: GPIO15
    id: relay

sensor:
  - platform: integration
    name: "Energie"
    sensor: power_wattage
    time_unit: h
    restore: true
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO04
    change_mode_every: 4
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    update_interval: 3s

    power:
      name: "${friendly_devicename} Leistung"
      unit_of_measurement: W
      id: power_wattage
      icon: mdi:lightning-bolt
      filters:
        - throttle_average: ${update_interval}

    voltage:
      name: "${friendly_devicename} Spannung"
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline
      disabled_by_default: true
      filters:
        - throttle_average: ${update_interval}

    current:
      name: "${friendly_devicename} Stromstärke"
      unit_of_measurement: A
      accuracy_decimals: 3
      icon: mdi:current-ac
      filters:
        - throttle_average: ${update_interval}

  - platform: total_daily_energy
    name: "Energie heute"
    power_id: power_wattage
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 3
    icon: mdi:calendar-clock
    disabled_by_default: true

