esp8266:
  board: esp8285

uart:
  rx_pin: GPIO3
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${devicename}_button_state"
    on_press:
      - switch.toggle: relay

  - platform: template
    name: "Sonoff POW Running"
    filters:
      - delayed_off: 15s
    lambda: |-
      if (isnan(id(power).state)) {
        return {};
      } else if (id(power).state > 4) {
        return true;
      } else {
        return false;
      }

switch:
  - platform: gpio
    id: relay
    name: ${friendly_devicename}
    pin: GPIO12
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    id: led
    name: "LED"
    output: pow_blue_led

sensor:
  - platform: cse7766
    current:
      name: "${friendly_devicename} Current"
      id: current
    voltage:
      name: "${friendly_devicename} Voltage"
      id: voltage
    power:
      name: "${friendly_devicename} Power"
      id: power
    energy:
      name: "${friendly_devicename} Energy"
      id: energy