---

# devicetypes/sonoff-pow-r2-switch.yaml

binary_sensor:
  - platform: gpio
    id: pow_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_devicename} Button State"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    id: relay
    name: ${relay_name}
    icon: ${relay_icon}
    pin: GPIO12
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

