---

# athompresence02.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "athompresence02"
  friendly_devicename: "Präsenz Keller"
  room: "Keller"
  comment: "Athom Presence Sensor Keller"
  project_name: "Athom.Presence Sensor"
  project_version: "1.0"

  # Custom substitutions

packages:
  # Basic configuration
  - !include common/section-esphome.yaml
  - !include common/section-system.yaml
  # Default components
  - !include components/binary_sensor.yaml
  - !include components/button.yaml
  - !include components/sensor.yaml
  - !include components/text_sensor.yaml
  - !include components/switch.yaml
  # Device type
  - !include device_types/athom-presence.yaml

