---

# athompresence02.yaml

substitutions:
  config_tested_date: "2026-06-02"
  devicename: "athompresence02"
  friendly_devicename: "Präsenz Keller"
  room: "Keller"
  comment: "Athom Presence Sensor Keller"
  project_name: "Athom.Presence Sensor"
  project_version: "2.0"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/athom/presence.yaml

