---

# athompresence03.yaml

substitutions:
  config_tested_date: "2026-06-02"
  devicename: "athompresence03"
  friendly_devicename: "Präsenz Küche"
  room: "Küche"
  comment: "Athom Presence Sensor Küche"
  project_name: "Athom.Presence Sensor"
  project_version: "2.0"

  language: "de_DE"
  measurement_units: "metric"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/athom/presence.yaml

