---

# esp32-cam-02.yaml

substitutions:
  devicename: "esp32-cam-02"
  friendly_devicename: "ESP32-Cam 02"
  room: "Auf Lager"
  comment: "ESP32-Cam 02"
  project_name: "Espressif.ESP32"
  project_version: "2.0"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/boards/esp32-generic.yaml
  role: !include roles/camera.yaml