---

# esp32-07.yaml

substitutions:
  config_tested_date: "2026-06-02"
  devicename: "esp32-07"
  friendly_devicename: "Display Bad"
  room: "Badezimmer"
  comment: "Bad Tür-Display"
  project_name: "Espressif.ESP32"
  project_version: "1.0"

  sda_pin: "GPIO33"
  scl_pin: "GPIO35"

  font_name: "materialdesignicons-webfont.ttf"
#   entity_to_watch: "binary_sensor.presence_bad_occupancy"
  entity_to_watch: binary_sensor.prasenz_keller_occupancy

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/boards/esp32-s2-generic.yaml
  role: !include roles/display-128x32.yaml

