---

# esp32-04.yaml

substitutions:
  config_tested_date: "2026-06-02"
  devicename: "esp32-04"
  friendly_devicename: "ESP32 04 Verschollen"
  room: "Auf Lager"
  comment: "ESP32 04 Verschollen"
  project_name: "Espressif.ESP32"
  project_version: "2.0"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/boards/esp32-generic.yaml