---

# esp32-01.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "esp32-01"
  friendly_devicename: "Regensensor"
  room: "Garten"
  comment: "Regensensor"
  project_name: "Espressif.ESP32"
  project_version: "1.0"

  # Custom substitutions
  # TODO: Handle case where resistance is higher than max_resistance
  resistor_value: "9.868kOhm"

  # Skip values outside this range
  min_resistance: "1000"
  max_resistance: "500000"

  # Resistance drop required to classify a new rain event
  rain_detection_threshold: "4000"

  # Resistance increase required to classify drying
  dry_detection_threshold: "4000"

  # On boot, if resistance is below this value, assume the sensor is wet
  wet_resistance_when_booting: "50000"

  # +------------------------------+
  # | Delay between rain measures  |
  # +------------------------------+
  # In dry mode
  measure_interval_dry: "5000"

  # In wet mode
  # Must be large enough to avoid wearing the sensor tracks too fast,
  # but small enough to stay responsive.
  measure_interval_wet: "30000"

  # Stabilization before reading the resistance.
  # A too short delay may prevent reliable low-resistance readings.
  stabilization_delay: 2sec

  adc_pin: "GPIO35"
  bias_pin: "GPIO32"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/boards/esp32-generic.yaml

