---

# esp32-cam-02.yaml

substitutions:
  devicename: "esp32-cam-02"
  friendly_devicename: "Berner Gary-Cam"
  room: "Auf Lager"
  comment: "Berner Gary-Cam"
  project_name: "Espressif.ESP32"
  project_version: "1.0"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/boards/esp32-generic.yaml
  role: !include roles/camera.yaml