# esp32-btproxy-02.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2006-06-03"
  devicename: "esp32-btproxy-02"
  friendly_devicename: "Bluetooth Proxy Esszimmer"
  room: "Esszimmer"
  comment: "ESP32 Bluetooth Proxy 02"
  project_name: "Espressif.ESP32"
  project_version: "1.0"

packages:
  # Basic configuration
  - !include common/section-esphome.yaml
  - !include common/section-system.yaml
  # Default components
  - !include components/binary_sensor.yaml
  - !include components/button.yaml
  - !include components/sensor.yaml
  - !include components/text_sensor.yaml
  - !include components/switch.yaml
  # Device type
  - !include devicetypes/esp32-generic.yaml
  - !include devicetypes/esp32-btproxy.yaml
  
  # Online version
  # esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main

# Custom configuration