---

# esp32-03.yaml

substitutions:
  config_tested_date: "2026-06-02"
  devicename: "esp32-03"
  friendly_devicename: "Fan-Controller"
  room: "Datacenter"
  comment: "Serverschrank Fan-Controller"
  project_name: "Espressif.ESP32"
  project_version: "1.0"

# Throttle writing parameters to the internal flash memory to reduce ESP memory wear / degradation
preferences:
  flash_write_interval: 15min

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/boards/esp32-generic.yaml
  role: !include roles/fan-controller.yaml

