---

# esp8266-03.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "esp8266-03"
  friendly_devicename: "Unbenutzt esp8266-03"
  room: "Auf Lager"
  comment: "Unbenutzt esp8266-03"
  project_name: "Wemos.D1 Mini ESP8266"
  project_version: "1.0"

  # Custom substitutions

packages:
  # Basic configuration
  - !include common/section-esphome.yaml
  - !include common/section-system.yaml
  # Default components
  - !include components/binary_sensor.yaml
  - !include components/button.yaml
  - !include components/sensor.yaml
  - !include components/text_sensor.yaml
  - !include components/switch.yaml
  # Device type
  - !include devicetypes/esp8266-d1-mini.yaml

