---

# esp8266-03.yaml

substitutions:
  devicename: "esp8266-03"
  friendly_devicename: "Kühlgefrierkombi"
  room: "Küche"
  comment: "Kühlgefrierkombi esp8266-03"
  project_name: "Wemos.D1 Mini ESP8266"
  project_version: "2.0"

  language: "de_DE"
  measurement_units: "metric"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/boards/esp8266-d1-mini.yaml