---

# esp8266-03.yaml

substitutions:
  devicename: "esp8266-03"
  friendly_devicename: "Kühlgefrierkombi"
  room: "Küche"
  comment: "Kühlgefrierkombi"
  project_name: "Wemos.D1 Mini ESP8266"
  project_version: "2.0"

  language: "de_DE"
  measurement_units: "metric"

  update_interval: 60s

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/boards/esp8266-d1-mini.yaml

  sensor_kuehlschrank: !include
    file: components/sensor/ds18b20.yaml
    vars:
      ds18b20_id: ds18b20_kuehlschrank
      ds18b20_name: "Kühlschrank"
      ds18b20_address: "0xAA00000000000000"  # ← echte Adresse eintragen

  sensor_gefrierfach: !include
    file: components/sensor/ds18b20.yaml
    vars:
      ds18b20_id: ds18b20_gefrierfach
      ds18b20_name: "Gefrierfach"
      ds18b20_address: "0xBB00000000000000"  # ← echte Adresse eintragen

one_wire:
  - platform: gpio
    pin: D4    # entspricht GPIO2