---

# esp8266-02.yaml

substitutions:
  config_tested_date: "2026-06-02"
  devicename: "esp8266-02"
  friendly_devicename: "Kamin"
  room: "Esszimmer"
  comment: "Kamin"
  project_name: "Wemos.D1 Mini ESP8266"
  project_version: "1.0"

  max6675_update_interval: 10s
  max6675_cs_pin: D8
  spi_miso_pin: D6
  spi_clk_pin: D5
  temperature_threshold: "40.0"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/boards/esp8266-d1-mini.yaml

spi:
  miso_pin: ${spi_miso_pin}
  clk_pin: ${spi_clk_pin}

sensor:
  - !include common/sensor/max6675.yaml

binary_sensor:
  - platform: template
    name: "Zustand"
    id: zustand
    icon: mdi:fireplace
    lambda: |-
      if (id(max6675_temperature).state > ${temperature_threshold}) {
        return true;
      } else {
        return false;
      }

