---

# esp8266-05

substitutions:
  config_tested_date: "2026-06-02"
  devicename: "esp8266-05"
  friendly_devicename: "Unbenutzt esp8266-05"
  room: "Auf Lager"
  comment: "Unbenutzt esp8266-05"
  project_name: "Wemos.D1 Mini ESP8266"
  project_version: "2.0"

  language: "de_DE"
  measurement_units: "metric"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/boards/esp8266-d1-mini.yaml