---

# esp8266-01.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "esp8266-01"
  friendly_devicename: "Bett Jan"
  room: "Jan"
  comment: "Jan Bettsensor"
  project_name: "Wemos.D1 Mini ESP8266"
  project_version: "1.0"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/boards/esp8266-d1-mini.yaml
  role: !include roles/camera.yaml
  - !include device_types/esp8266-d1-mini.yaml
  - !include roles/scale.yaml

