---

# gosundplug03.yaml

substitutions:
  config_tested_date: "2026-06-02"
  devicename: "gosundplug-03"
  friendly_devicename: "Laserdrucker"
  room: "Keller"
  comment: "Gosund SP111 Laserdrucker"
  project_name: "Gosund.SP111"
  project_version: "2.0"

  relay_name: "${friendly_devicename}"
  relay_icon: "mdi:printer"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/gosund/sp111-switch.yaml

