---

# gosundplug09.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "gosundplug09"
  friendly_devicename: "Kühlschrank"
  room: "Küche"
  comment: "Gosund SP111 Kühlschrank"
  project_name: "Gosund.SP111"
  project_version: "2.0"

  relay_name: "${friendly_devicename}"
  relay_icon: "mdi:fridge"

  language: "de_DE"
  measurement_units: "metric"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/gosund/sp111-switch.yaml
