---

# gosundplug11.yaml

substitutions:
  config_tested_date: "2026-06-02"
  devicename: "gosundplug11"
  friendly_devicename: "3D-Drucker"
  room: "Abseite UG"
  comment: "Gosund SP111 3D-Drucker"
  project_name: "Gosund.SP111"
  project_version: "2.0"

  language: "de_DE"
  measurement_units: "metric"

  relay_name: "${friendly_devicename}"
  relay_icon: "mdi:printer-3d"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/gosund/sp111-switch.yaml
