---

# gosundplug12.yaml

substitutions:
  config_tested_date: "2026-06-02"
  devicename: "gosundplug12"
  friendly_devicename: "Schreibtisch"
  room: "Steffi"
  comment: "Gosund SP111 Schreibtisch"
  project_name: "Gosund.SP111"
  project_version: "2.0"

  language: "de_DE"
  measurement_units: "metric"

  relay_name: "${friendly_devicename}"
  relay_icon: "mdi:desk"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/gosund/sp111-switch.yaml
