---

# gosundplug03.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "gosundplug03"
  friendly_devicename: "Laserdrucker"
  room: "Keller"
  comment: "Gosund SP111 Laserdrucker"
  project_name: "Gosund.SP111"
  project_version: "1.0"

  # Custom substitutions  
  relay_name: "${friendly_devicename}"
  relay_icon: "mdi:printer"

packages:
  # Basic configuration
  - !include common/section-esphome.yaml
  - !include common/section-system.yaml
  # Default components
  - !include components/binary_sensor.yaml
  - !include components/button.yaml
  - !include components/sensor.yaml
  - !include components/text_sensor.yaml
  - !include components/switch.yaml
  # Device type
  - !include device_types/gosund-sp111-generic.yaml
  - !include device_types/gosund-sp111-switch.yaml

