# powerstrip01.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "powerstrip-01"
  friendly_devicename: "Powerstrip Flur EG"
  room: "Flur EG"
  comment: "Blitzwolf SHP9 Powerstrip Flur EG"
  project_name: "Blitzwolf.SHP9"
  project_version: "1.0"

  # Custom substiturions
  # Sockets
  relay_1_name: "Kellertreppe"
  relay_1_icon: "mdi:stairs-down"
  relay_2_name: "Staubsauger"
  relay_2_icon: "mdi:vacuum"
  relay_3_name: "Sockel 3"
  relay_3_icon: "mdi:power-socket-de"
  # USB ports
  relay_4_name: "USB"
  relay_4_icon: "mdi:usb"

packages:
  # Basic configuration
  - !include common/section-esphome.yaml
  - !include common/section-system.yaml
  # Default components
  - !include components/binary_sensor.yaml
  - !include components/button.yaml
  - !include components/sensor.yaml
  - !include components/text_sensor.yaml
  - !include components/switch.yaml
  # Device type
  - !include devicetypes/blitzwolf-shp9.yaml

# Custom configuration

