# powerstrip01.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "powerstrip-01"
  friendly_devicename: "Powerstrip Flur EG"
  room: "Flur EG"
  comment: "Blitzwolf SHP9 Powerstrip Flur EG"
  project_name: "Blitzwolf.SHP9"
  project_version: "1.0"

  # Custom substiturions
  socket_name_1: "Kellertreppe"
  socket_name_2: "Kellertreppe"
  socket_name_3: "Sockel 3"
  socket_name_usb: "USB"

packages:
  # Basic configuration
  - !include common/section-esphome.yaml
  - !include common/section-system.yaml
  # Default components
  - !include components/binary_sensor.yaml
  - !include components/button.yaml
  - !include components/sensor.yaml
  - !include components/text_sensor.yaml
  - !include components/switch.yaml
  # Device type
  - !include devicetypes/blitzwolf-shp9.yaml

# Custom configuration

