---

# powerstrip01.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "powerstrip-01"
  friendly_devicename: "Powerstrip Flur EG"
  room: "Flur EG"
  comment: "Blitzwolf SHP9 Powerstrip Flur EG"
  project_name: "Blitzwolf.SHP9"
  project_version: "1.0"

  # Custom substiturions
  # Sockets
  relay_1_name: "Staubsauger"
  relay_1_icon: "mdi:vacuum"

  relay_2_name: "Kellertreppe"
  relay_2_icon: "mdi:stairs-down"

  relay_3_name: "Sockel 3"
  relay_3_icon: "mdi:power-socket-de"
  
  # USB ports
  relay_4_name: "USB"
  relay_4_icon: "mdi:usb"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/gosund/blitzwolf/shp9.yaml

  - !include device_types/

