# rpi-pico-04.yaml

substitutions:
  # Default substitutions
  config_tested_date: "XXX"
  devicename: "rpi-pico-04"
  friendly_devicename: "Raspberry Pi Pico W 04"
  room: "Auf Lager"
  comment: "Raspberry Pi Pico W 04"
  project_name: "Raspberry Pi.Pico W"
  project_version: "1.0"

packages:
  # Basic configuration
  - !include common/section-esphome.yaml
  - !include common/section-system.yaml
  # Default components
  - !include components/binary_sensor.yaml
  - !include components/button.yaml
  - !include components/sensor.yaml
  - !include components/text_sensor.yaml
  - !include components/switch.yaml
  # Device type
  - !include devicetypes/raspberrypi-pico-w.yaml

# Custom configuration