---

# rpi-pico-01.yaml

substitutions:
  # Default substitutions
  config_tested_date: "XXX"
  devicename: "rpi-pico-01"
  friendly_devicename: "Raspberry Pi Pico W 01"
  room: "Auf Lager"
  comment: "Raspberry Pi Pico W 01"
  project_name: "Raspberry Pi.Pico W"
  project_version: "1.0"

packages:
  # Basic configuration
  - !include common/base-system.yaml
  - !include common/section-system.yaml
  # Default components
  - !include components/binary_sensor.yaml
  - !include components/button.yaml
  - !include components/sensor.yaml
  - !include components/text_sensor.yaml
  - !include components/switch.yaml
  # Device type
  device_type: !include device_types/raspberrypi/pico-w.yaml

