---

# sonoffbasicr2-01.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "sonoffbasicr2-03"
  friendly_devicename: "Licht Keller Waschbecken"
  room: "Keller"
  comment: "Licht Keller Waschbecken"
  project_name: "Sonoff.Basic R2"
  project_version: "2.0"

  relay_name: "${friendly_devicename}"
  relay_icon: "phu:ceiling-aurelle"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/sonoff/basic-r2-light.yaml

