---

# sonoffpowr2-03.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-04"
  devicename: "sonoffpowr2-02"
  friendly_devicename: "Trockner"
  room: "Keller"
  comment: "Sonoff POW R2 Trockner"
  project_name: "Sonoff.POW R2"
  project_version: "1.0"

  # Custom substitutions
  update_interval: 10s
  
  relay_name: "Trockner"
  relay_icon: "mdi:tumble-dryer"

  energy_total_offset: "1058.60" # Migrated from Tasmota 2026-06-04

packages:
  # Basic configuration
  - !include common/section-esphome.yaml
  - !include common/section-system.yaml
  # Default components
  - !include components/binary_sensor.yaml
  - !include components/button.yaml
  - !include components/sensor.yaml
  - !include components/text_sensor.yaml
  - !include components/switch.yaml
  # Device type
  - !include devicetypes/sonoff-pow-r2-generic.yaml
  - !include devicetypes/sonoff-pow-r2-switch.yaml

# Custom configuration

