---

# sonoffpowr2-03.yaml

substitutions:
  devicename: "sonoffpowr2-03"
  friendly_devicename: "Trockner"
  room: "Keller"
  comment: "Sonoff POW R2 Trockner"
  project_name: "Sonoff.POW R2"
  project_version: "2.0"

  language: "de_DE"
  measurement_units: "metric"

  relay_name: "${friendly_devicename}"
  relay_icon: "mdi:tumble-dryer"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/sonoff/pow-r2-switch.yaml
#   base_network_esp: !include common/base-network-esp.yaml

# esp8266:
#   board: esp8285

# logger:
#   baud_rate: 0
#   level: DEBUG

# uart:
#   rx_pin: RX
#   baud_rate: 4800
#   parity: EVEN


# sensor:
#   - platform: cse7766
#     voltage:
#       name: "Voltage"
#       filters:
#         - throttle_average: 60s
#     current:
#       name: "Current"
#       filters:
#         - throttle_average: 60s
#     power:
#       name: "Power"
#       filters:
#         - throttle_average: 60s
#     energy:
#       name: "Energy"
#       filters:
#         - throttle: 60s

# switch:
#   - platform: gpio
#     name: "Relay"
#     pin: GPIO12