---

# sonoffpowr2-01.yaml

substitutions:
  devicename: "sonoffpowr2-01"
  friendly_devicename: "Licht Hintergrund"
  room: "Wohnzimmer"
  comment: "Sonoff POW R2 Licht Wohnzimmer Hintergrund"
  project_name: "Sonoff.POW R2"
  project_version: "2.0"

  language: "de_DE"
  measurement_units: "metric"

  relay_name: "${friendly_devicename}"
  relay_icon: "mdi:lightbulb-spot"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/sonoff/pow-r2-light.yaml

