---

# sonoffbasicr2-02.yaml

substitutions:
  # Default substitutions
  devicename: "sonoffbasicr2-02"
  friendly_devicename: "Licht Keller Arbeitsplatte"
  room: "Keller"
  comment: "Licht Keller Arbeitsplatte"
  project_name: "Sonoff.Basic R2"
  project_version: "2.0"

  language: "de_DE"
  measurement_units: "metric"

  relay_name: "${friendly_devicename}"
  relay_icon: "phu:ceiling-aurelle"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/sonoff/basic-r2-light.yaml


