---

# sonoffbasicr2-01.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "sonoffbasicr2-04"
  friendly_devicename: "Licht Abseite UG"
  room: "Abseite UG"
  comment: "Licht Abseite UG"
  project_name: "Sonoff.Basic R2"
  project_version: "1.0"

packages:
  # Basic configuration
  - !include common/base-system.yaml
  - !include common/section-system.yaml
  # Default components
  - !include components/binary_sensor.yaml
  - !include components/button.yaml
  - !include components/sensor.yaml
  - !include components/text_sensor.yaml
  - !include components/switch.yaml
  # Device type
  - !include device_types/sonoff-basic-r2.yaml

