---

# sonoffpowr2-02.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-04"
  devicename: "sonoffpowr2-02"
  friendly_devicename: "Waschmaschine"
  room: "Keller"
  comment: "Sonoff POW R2 Waschmaschine"
  project_name: "Sonoff.POW R2"
  project_version: "1.0"

  # Custom substitutions  
  relay_name: "${friendly_devicename}"
  relay_icon: "mdi:washing-machine"

packages:
  # Basic configuration
  - !include common/section-esphome.yaml
  - !include common/section-system.yaml
  # Default components
  - !include components/binary_sensor.yaml
  - !include components/button.yaml
  - !include components/sensor.yaml
  - !include components/text_sensor.yaml
  - !include components/switch.yaml
  # Device type
  - !include devicetypes/sonoff-pow-r2-generic.yaml
  - !include devicetypes/sonoff-pow-r2-switch.yaml

