---

# sonoffbasicr2-02.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "sonoffbasicr2-02"
  friendly_devicename: "Licht Keller Arbeitsplatte"
  room: "Keller"
  comment: "Licht Keller Arbeitsplatte"
  project_name: "Sonoff.Basic R2"
  project_version: "1.0"

  relay_name: "${friendly_devicename}"
  relay_icon: "mdi:led-panel"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/sonoff/basic-r2-light.yaml


