---

# star-projector-01.yaml

substitutions:
  devicename: "star-projector-jan"
  friendly_devicename: "Star Projector Jan"
  room: "Jan"
  comment: "Star Projector Jan"
  project_name: "Espressif.ESP32"
  project_version: "2.0"

  language: "de_DE"
  measurement_units: "metric"

  node_name: "star_projector_jan"

packages:
  default_package: !include common/base-device.yaml
  device_type: !include device_types/tuya/bk7231t-qfn32.yaml

