---

# star-projector-01.yaml

substitutions:
  # Default substitutions
  config_tested_date: "2026-06-02"
  devicename: "star-projector-jan"
  friendly_devicename: "Star Projector Jan"
  room: "Jan"
  comment: "Star Projector Jan"
  project_name: "Espressif.ESP32"
  project_version: "1.0"

  # Custom substitutions
  node_name: "star_projector_jan"

packages:
  # Basic configuration
  - !include common/section-esphome.yaml
  - !include common/section-system.yaml
  # Default components
  - !include components/binary_sensor.yaml
  - !include components/button.yaml
  - !include components/sensor.yaml
  - !include components/text_sensor.yaml
  - !include components/switch.yaml
  # Device type
  - !include devicetypes/generic-bk7231t-qfn32-tuya.yaml

---
