---

# common/lang/de_DE.yaml

substitutions:
  sensor_name_status: "Status"
  sensor_name_uptime: "Laufzeit"
  sensor_name_wifi_signal_db: "WLAN-Signal dB"
  sensor_name_version: "Firmware"
  sensor_name_config_tested: "Konfiguration getestet"
  sensor_name_devicename: "Gerätename"
  sensor_name_devicename_friendly: "Anzeigename"
  sensor_name_ip_address: "IP-Adresse"
  sensor_name_connected_ssid: "Verbundenes WLAN"
  sensor_name_connected_bssid: "Verbundenes BSSID"
  sensor_name_mac_address: "MAC-Adresse"
  sensor_name_latest_scan_results: "Letzte WLAN-Suche"
  sensor_name_dns_address: "DNS-Adresse"

  sensor_name_button_state: "Tasterstatus"
  sensor_name_active: "Aktiv"
  sensor_name_compiled_at: "Kompiliert am"

  sensor_name_power: "Leistung"
  sensor_name_voltage: "Spannung"
  sensor_name_current: "Stromstärke"
  sensor_name_energy: "Energie"
  sensor_name_energy_today: "Energie heute"
  sensor_name_apparent_power: "Scheinleistung"
  sensor_name_reactive_power: "Blindleistung"
  sensor_name_power_factor: "Leistungsfaktor"

  control_name_restart: "Neustart"
  control_name_safe_mode_boot: "Sicherer Start"
  control_name_factory_reset: "Werkseinstellungen"
  control_name_on_after_boot: "Einschalten beim Start"
  control_name_enable_button: "Taster aktivieren"
  control_name_allow_turn_off: "Ausschalten erlauben"
  control_name_enable_led: "LED aktivieren"

  sensor_name_temperature: "Temperatur"
  sensor_name_absolute_humidity: "Absolute Luftfeuchtigkeit"
  sensor_name_relative_humidity: "Relative Luftfeuchtigkeit"
  sensor_name_pressure: "Luftdruck"
  sensor_name_dew_point: "Taupunkt"
  sensor_name_elevation: "Höhe"
  sensor_name_co2_equivalent: "CO2 Equivalent"
  sensor_name_breath_voc_equivalent: "Atem VOC Equivalent"
  sensor_name_gas_resistance: "Gas Widerstand"
  sensor_name_iaq: "Luftqualität"
  sensor_name_distance: "Entfernung"
  sensor_name_pir: "PIR"
  sensor_name_mmwave: "mmWave"
  sensor_name_mmwave_status: "mmWave Status"
  sensor_name_occupancy: "Belegt"
  sensor_name_light: "Licht"