---

# components/sensor/aht30.yaml

substitutions:
  update_interval: 60s

platform: aht10
temperature:
  id: aht10_temperature_sensor
  name: ${sensor_name_temperature}
  icon: ${icon_temperature}
humidity:
  id: aht10_relative_humidity_sensor
  name: ${sensor_name_relative_humidity}
  icon: ${icon_relative_humidity}
  accuracy_decimals: 1
update_interval: ${update_interval}
address: 0x38

