---

# components/sensor/bme280.yaml

substitutions:
  update_interval: 60s

platform: bme280
temperature:
  id: bme280_temperature_sensor
  name: ${sensor_name_temperature}
  icon: ${icon_temperature}
pressure:
  id: bme280_pressure_sensor
  name: ${sensor_name_pressure}
  icon: ${icon_pressure}
humidity:
  id: bme280_relative_humidity_sensor
  name: ${sensor_name_relative_humidity}
  icon: ${icon_relative_humidity}
address: 0x77
update_interval: ${update_interval}

platform: template
name: ${sensor_name_elevation}
icon: ${icon_elevation}
lambda: |-
  const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
  return ((id(temperature_sensor).state + 273.15) / 0.0065) *
    (powf((STANDARD_SEA_LEVEL_PRESSURE / id(bme280_pressure_sensor).state), 0.190234) - 1); // in meter
update_interval: ${update_interval}
unit_of_measurement: ${unit_distance_long}

platform: absolute_humidity
name: ${sensor_name_absolute_humidity}
icon: ${icon_absolute_humidity}
temperature: bme280_temperature_sensor
humidity: bme280_humidity_sensor

platform: template
name: ${sensor_name_thaw_point}
icon: ${icon_thaw_point}
lambda: |-
  return (243.5*(log(id(bme280_humidity_sensor).state/100)+((17.67*id(bme280_temperature_sensor).state)/
  (243.5+id(bme280_temperature_sensor).state)))/(17.67-log(id(bme280_humidity_sensor).state/100)-
  ((17.67*id(bme280_temperature_sensor).state)/(243.5+id(bme280_temperature_sensor).state))));
unit_of_measurement: ${unit_temperature}

