---

# components/sensor/max6675.yaml

platform: max6675
name: ${sensor_name_temperature}
icon: ${icon_temperature}
id: max6675_temperature
cs_pin: ${cs_pin}
update_interval: ${update_interval}
unit_of_measurement: ${unit_temperature}
device_class: temperature
state_class: measurement
accuracy_decimals: 1

